config/routes.rb
Rails.application.routes.draw do
  resources :games
  get 'download_pdf', to: "games#download_pdf", as: 'download_pdf'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many_attached :images
  has_one_attached :insruction
    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :delete_image,
     :delete_avatar, :delete_insruction]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end


  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :insruction, :rule, :avatar, images:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Name</label>
    <%= form.text_field :name %>
  </div>

    <div class="form-group">
      <label for="exampleInputEmail1" class="h3">Rule</label>
    <%= form.text_area :rule %>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Insruction</label>
  <%= form.file_field :insruction %>
  </div>
<br>
<br>

<div class="form-group">
  <label for="exampleInputEmail1" class="h3">La foto de las piezas</label>
<%= form.file_field :avatar %>
</div>
<br>
<br>

<div class="form-group">
  <label for="exampleInputEmail1" class="h3">Las fotos de  partes del tablero</label>
<%= form.label "Las fotos de  partes del tablero "%><%= form.file_field :images, multiple: true %>
</div>
<br>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<form>
  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Name:</label>
      <label for="exampleInputEmail1"><%= @game.name %></label>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Rule:</label>
    <label for="exampleInputEmail1"><%= @game.rule %></label>
  </div>

<div class="form-group">
  <label for="exampleInputEmail1" class="h3">Insruction eb PDF:</label>
  <% @game.insruction %>
  <a href="<%= rails_blob_path(@game.insruction, disposition: "attachment") %>" > Descargar PDF</a>
  </div>


  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Las foto de las piezas:</label>
<% if @game.avatar.attached? %>
<p>
<%= image_tag @game.avatar, style: "-webkit-filter: grayscale(100%) height:150px;width:150px" %>
</p>
<% end %>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1" class="h3">Las fotos de  partes del tablero</label>
<% if @game.images.attached? %>
<p>

<br>
<% @game.images.each do |image| %>
<%= image_tag image, style: "-webkit-filter: grayscale(100%) height:150px;width:150px" %>

<% end %>
</p>
<% end %>
  </div>


</form>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuegoDeMesa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>